# Generated by Django 5.0.4 on 2024-05-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=45)),
                ('familya', models.CharField(max_length=45)),
                ('adress', models.CharField(max_length=45)),
                ('tel', models.CharField(max_length=45)),
                ('yosh', models.IntegerField()),
            ],
        ),
    ]
